#pragma once

namespace AVL {

    /* From https://asawicki.info/nosense/doc/devices/keyboard/key_codes.html */
    enum KeyCode {

        Backspace       = 8 ,
        Tab             = 9 ,
        Enter           = 13,
        Shift           = 16,
        Ctrl            = 17,
        Alt             = 18,
        Pause           = 19,
        CapsLock        = 20,
        Esc             = 27,
        Space           = 32,
        PageUp          = 33,
        PageDown        = 34,
        End             = 35,
        Home            = 36,
        Leftarrow       = 37,
        Uparrow         = 38,
        RightArrow      = 39,
        DownArrow       = 40,
        PrintScreen     = 44,
        Insert          = 45,
        Delete          = 46,

        D0              = 48,
        D1              = 49,
        D2              = 50,
        D3              = 51,
        D4              = 52,
        D5              = 53,
        D6              = 54,
        D7              = 55,
        D8              = 56,
        D9              = 57,

        A               = 65,
        B               = 66,
        C               = 67,
        D               = 68,
        E               = 69,
        F               = 70,
        G               = 71,
        H               = 72,
        I               = 73,
        J               = 74,
        K               = 75,
        L               = 76,
        M               = 77,
        N               = 78,
        O               = 79,
        P               = 80,
        Q               = 81,
        R               = 82,
        S               = 83,
        T               = 84,
        U               = 85,
        V               = 86,
        W               = 87,
        X               = 88,
        Y               = 89,
        Z               = 90,


        LeftWin         = 91,
        RightWin        = 92,
        Popup           = 93,

        DN0             = 96,
        DN1             = 97,
        DN2             = 98,
        DN3             = 99,
        DN4             = 100,
        DN5             = 101,
        DN6             = 102,
        DN7             = 103,
        DN8             = 104,
        DN9             = 105,
        DNMult          = 106,
        DNPlus          = 107,
        DNMinus         = 109,
        DNPoint         = 110,
        DNDivide        = 111,

        F1              = 112,
        F2              = 113,
        F3              = 114,
        F4              = 115,
        F5              = 116,
        F6              = 117,
        F7              = 118,
        F8              = 119,
        F9              = 120,
        F10             = 121,
        F11             = 122,
        F12             = 123,

        NumLock         = 144,
        ScrollLock      = 145,
        LeftShift       = 160,
        RightShift      = 161,
        LeftCtrl        = 162,
        RightCtrl       = 163
    };

    std::map<KeyCode, std::string> KeyNames {
        std::make_pair(Backspace    , "Backspace"),
        std::make_pair(Tab          ,"Tab"),
        std::make_pair(Enter        ,"Enter"),
        std::make_pair(Shift        ,"Shift"),
        std::make_pair(Ctrl         ,"Ctrl"),
        std::make_pair(Alt          ,"Alt"),
        std::make_pair(Pause        , "Pause"),
        std::make_pair(CapsLock     , "CapsLock"),
        std::make_pair(Esc          , "Esc"),
        std::make_pair(Space        , "Space"),
        std::make_pair(PageUp       , "PageUp"),
        std::make_pair(PageDown     , "PageDown"),
        std::make_pair(End          , "End"),
        std::make_pair(Home         , "Home"),
        std::make_pair(Leftarrow    , "Leftarrow"),
        std::make_pair(Uparrow      , "Uparrow"),
        std::make_pair(RightArrow   , "RightArrow"),
        std::make_pair(DownArrow    , "DownArrow"),
        std::make_pair(PrintScreen  , "PrintScreen"),
        std::make_pair(Insert       , "Insert"),
        std::make_pair(Delete       , "Delete"),
        std::make_pair(D0           , "D0"),
        std::make_pair(D1           , "D1"),
        std::make_pair(D2           , "D2"),
        std::make_pair(D3           , "D3"),
        std::make_pair(D4           , "D4"),
        std::make_pair(D5           , "D5"),
        std::make_pair(D6           , "D6"),
        std::make_pair(D7           , "D7"),
        std::make_pair(D8           , "D8"),
        std::make_pair(D9           , "D9"),
        std::make_pair(A            , "A"),
        std::make_pair(B            , "B"),
        std::make_pair(C            , "C"),
        std::make_pair(D            , "D"),
        std::make_pair(E            , "E"),
        std::make_pair(F            , "F"),
        std::make_pair(G            , "G"),
        std::make_pair(H            , "H"),
        std::make_pair(I            , "I"),
        std::make_pair(J            , "J"),
        std::make_pair(K            , "K"),
        std::make_pair(L            , "L"),
        std::make_pair(M            , "M"),
        std::make_pair(N            , "N"),
        std::make_pair(O            , "O"),
        std::make_pair(P            , "P"),
        std::make_pair(Q            , "Q"),
        std::make_pair(R            , "R"),
        std::make_pair(S            , "S"),
        std::make_pair(T            , "T"),
        std::make_pair(U            , "U"),
        std::make_pair(V            , "V"),
        std::make_pair(W            , "W"),
        std::make_pair(X               , "X"),
        std::make_pair(Y               , "Y"),
        std::make_pair(Z               , "Z"),
        std::make_pair(LeftWin         , "LeftWin"),
        std::make_pair(RightWin        , "RightWin"),
        std::make_pair(Popup           , "Popup"),
        std::make_pair(DN0             , "DN0"),
        std::make_pair(DN1             , "DN1"),
        std::make_pair(DN2             , "DN2"),
        std::make_pair(DN3             , "DN3"),
        std::make_pair(DN4             , "DN4"),
        std::make_pair(DN5             , "DN5"),
        std::make_pair(DN6             , "DN6"),
        std::make_pair(DN7             , "DN7"),
        std::make_pair(DN8             , "DN8"),
        std::make_pair(DN9             , "DN9"),
        std::make_pair(DNMult          , "DNMult"),
        std::make_pair(DNPlus          , "DNPlus"),
        std::make_pair(DNMinus         , "DNMinus"),
        std::make_pair(DNPoint         , "DNPoint"),
        std::make_pair(DNDivide        , "DNDivide"),
        std::make_pair(F1              , "F1"),
        std::make_pair(F2              , "F2"),
        std::make_pair(F3              , "F3"),
        std::make_pair(F4              , "F4"),
        std::make_pair(F5              , "F5"),
        std::make_pair(F6              , "F6"),
        std::make_pair(F7              , "F7"),
        std::make_pair(F8              , "F8"),
        std::make_pair(F9              , "F9"),
        std::make_pair(F10             , "F10"),
        std::make_pair(F11             , "F11"),
        std::make_pair(F12             , "F12"),
        std::make_pair(NumLock         , "NumLock"),
        std::make_pair(ScrollLock      , "ScrollLock"),
        std::make_pair(LeftShift       , "LeftShift"),
        std::make_pair(RightShift      , "RightShift"),
        std::make_pair(LeftCtrl        , "LeftCtrl"),
        std::make_pair(RightCtrl       , "RightCtrl")
    };
}